<?php

namespace application\dovahkiin\models;

use Next\Exception;

use Next\Core\Utils\ArrayUtils;

/**
 * Dragon Alphabet for Dovahkiin Application
 */

abstract class Alphabet {

    protected static $alphabet = array(

        array( 'Aak', 'Guide' ),
        array( 'Aal', 'May', 'as in &quot;May his soul&quot;' ),
        array( 'Aam', 'Hmm?', 'expression of disbelief' ),
        array( 'Aan', 'A/An' ),
        array( 'Aar', 'Servant' ),
        array( 'Aav', 'Join' ),
        array( 'Aaz', 'Mercy' ),
        array( 'Ag', 'Burn' ),
        array( 'Ah', 'Hunter' ),
        array( 'Ahmik', 'Service' ),
        array( 'Ahmul', 'Husband' ),
        array( 'Ahkrin', 'Courage' ),
        array( 'Ahraan', 'Wound', 'noun' ),
        array( 'Ahrk', 'And' ),
        array( 'Ahrol', 'Hill', NULL, '[3]' ),
        array( 'Ahst', 'At', NULL, '[2]' ),
        array( 'Ahzid', 'Bitter' ),
        array( 'Al', 'Destroyer' ),
        array( 'Alok', 'Arise' ),
        array( 'Alok-Dilon', 'Necromancy', NULL, '[4]' ),
        array( 'Alun', 'Ever' ),
        array( 'Askk', 'Love' ),
        array( 'Aus', 'Suffer' ),
        array( 'Bah', 'Wrath' ),
        array( 'Bahlok', 'Hunger' ),
        array( 'Banaar', 'Humble' ),
        array( 'Bein', 'Foul' ),
        array( 'Beyn', 'Scorn' ),
        array( 'Bex', 'Open', NULL, '[5]' ),
        array( 'Bodiis', 'Borrow' ),
        array( 'Bormah', 'Father' ),
        array( 'Bovul', 'Flee / Fled', NULL, '[6]' ),
        array( 'Boziik', 'Bold / Boldly' ),
        array( 'Brendon', 'Specter' ),
        array( 'Brii', 'Beauty' ),
        array( 'Briinah', 'Sister' ),
        array( 'Brit', 'Beautiful' ),
        array( 'Brod', 'Clan' ),
        array( 'Brom', 'North' ),
        array( 'Bron', 'Nord' ),
        array( 'Bruniik', 'Savage' ),
        array( 'Du\'ul', 'Crown', NULL, '[7]' ),
        array( 'Daanik', 'Doomed', NULL, '[6]' ),
        array( 'Dah', 'Push' ),
        array( 'Dahmaan', 'Remember' ),
        array( 'Daal', 'Return' ),
        array( 'Daar', 'This / These' ),
        array( 'Denek', 'Soil' ),
        array( 'Dein', 'Keep' ),
        array( 'Dez', 'Fate' ),
        array( 'Diil', 'Undead', NULL, '[8]' ),
        array( 'Diin', 'Freeze' ),
        array( 'Diivon', 'Swallow' ),
        array( 'Dir', 'Die' ),
        array( 'Dinok', 'Death' ),
        array( 'Dilon', 'Dead' ),
        array( 'Do', 'Of / About' ),
        array( 'Dok', 'Hound' ),
        array( 'Dov', 'Dragonkind', 'referring to the race of dragons' ),
        array( 'Dovah', 'Dragon' ),
        array( 'Dovahgolz', 'Dragonstone' ),
        array( 'Dovahkiin', 'Dragonborn' ),
        array( 'Draal', 'Pray' ),
        array( 'Dreh', 'Do / Does' ),
        array( 'Drem', 'Peace / Patience' ),
        array( 'Drem Yol Lok', 'Greetings', 'literally &quot;peace fire sky&quot;' ),
        array( 'Drey', 'Did', NULL, '[6]' ),
        array( 'Drog', 'Lord' ),
        array( 'Drun', 'Bring/Brought' ),
        array( 'Du', 'Devour' ),
        array( 'Dur', 'Curse' ),
        array( 'Dukaan', 'Dishonour' ),
        array( 'Dun', 'Grace' ),
        array( 'Dwiin', 'Steel' ),
        array( 'Dwiirok', 'Carve' ),
        array( 'Ek', 'Her' ),
        array( 'Enook', 'Each' ),
        array( 'Ensosin', 'Bewitch' ),
        array( 'Evenaar', 'Extinguish' ),
        array( 'Evgir', 'Season' ),
        array( 'Faad', 'Warmth' ),
        array( 'Faal', 'The', 'formal, preceeding a proper noun, &quot;Faal Krein&quot; for &quot;The Sun&quot;' ),
        array( 'Faas', 'Fear' ),
        array( 'Faasnu', 'Fearless' ),
        array( 'Fah', 'For' ),
        array( 'Fahdon', 'Friend' ),
        array( 'Fahliil', 'Elf' ),
        array( 'Feim', 'Fade' ),
        array( 'Fel', 'Feral' ),
        array( 'Fen', 'Will' ),
        array( 'Fent', 'Shall' ),
        array( 'Feykro', 'Forest' ),
        array( 'Feyn', 'Bane' ),
        array( 'Fiik', 'Mirror' ),
        array( 'Filok', 'Escape' ),
        array( 'Fin', 'The', 'rarely used' ),
        array( 'Fo', 'Frost' ),
        array( 'Fod', 'When' ),
        array( 'Fodiiz', 'Hoar' ),
        array( 'Folaas', 'Wrong' ),
        array( 'Folook', 'Haunt' ),
        array( 'Fonaar', 'Charge' ),
        array( 'Frin', 'Hot' ),
        array( 'Frod', 'Field' ),
        array( 'Fron', 'Kin / Related' ),
        array( 'Frul', 'Ephemeral / Temporary' ),
        array( 'Ful', 'So' ),
        array( 'Fun', 'Told' ),
        array( 'Fundein', 'Unfurl / Unfurled' ),
        array( 'Funt', 'Fail' ),
        array( 'Fus', 'Force' ),
        array( 'Gaaf', 'Ghost' ),
        array( 'Gaan', 'Stamina' ),
        array( 'Gahrot', 'Steal', NULL, '[6]' ),
        array( 'Geh', 'Yes' ),
        array( 'Gein', 'One', 'to a single person or thing' ),
        array( 'Geinmaar', 'Oneself' ),
        array( 'Gogil', 'Goblin' ),
        array( 'Gol', 'Earth' ),
        array( 'Golt', 'Ground' ),
        array( 'Golz', 'Stone' ),
        array( 'Govey', 'Remove' ),
        array( 'Graan', 'Rout', 'verb' ),
        array( 'Grah', 'Battle' ),
        array( 'Grahmindol', 'Stratagem' ),
        array( 'Grah-Zeymahzin', 'Ally', 'Battle-Brother-Honor', '[4]' ),
        array( 'Gravuun', 'Autumn', NULL, '[6]' ),
        array( 'Grik', 'Such' ),
        array( 'Grind', 'Meet' ),
        array( 'Grohiik', 'Wolf' ),
        array( 'Gron', 'Bind' ),
        array( 'Gut', 'Far' ),
        array( 'Haal', 'Hand' ),
        array( 'Haas', 'Health' ),
        array( 'Haalvut', 'Touch', 'noun or verb' ),
        array( 'Hadrim, Hahdrim', 'Mind', 'noun' ),
        array( 'Hahkun', 'Axe' ),
        array( 'Hahnu', 'Dream' ),
        array( 'Heim', 'Forge' ),
        array( 'Het', 'Here' ),
        array( 'Hevno', 'Brutal' ),
        array( 'Heyv', 'Duty' ),
        array( 'Him(Hiu)', 'You/Your', 'rarely used' ),
        array( 'Hind', 'Wish, Hope' ),
        array( 'Hin(Hio)', 'Your/You', 'formal' ),
        array( 'Hofkah', 'Steading', NULL, '[9]' ),
        array( 'Hokoron', 'Enemy / Enemies' ),
        array( 'Horvut', 'Lure' ),
        array( 'Horvutah', 'Caught' ),
        array( 'Hon', 'Hear', '&quot;Nust hon&quot; - They hear' ),
        array( 'Hun', 'Hero' ),
        array( 'Huzrah', 'Hearken' ),
        array( 'Iiz', 'Ice' ),
        array( 'In', 'Master' ),
        array( 'Jer', 'East' ),
        array( 'Joor(re)', 'Mortal(s)' ),
        array( 'Jot', 'Maw' ),
        array( 'Jul', 'Man / Mankind / Humans', 'see also &quot;Muz&quot;' ),
        array( 'Jun', 'King, Light' ),
        array( 'Junnesejer', 'Kings of the East' ),
        array( 'Kaal', 'Champion' ),
        array( 'Kaan', 'Kyne' ),
        array( 'Kaaz', 'Cat / Khajiit' ),
        array( 'Kah', 'Pride' ),
        array( 'Kein', 'War' ),
        array( 'Keizaal', 'Skyrim' ),
        array( 'Kel(le)', 'SAcroll(s)', 'as in &quot;Elder Scrolls' ),
        array( 'Kendov', 'Warrior' ),
        array( 'Kest', 'Tempest' ),
        array( 'Key', 'Horse' ),
        array( 'Keyn', 'Anvil' ),
        array( 'Kiin', 'Born' ),
        array( 'Kiir', 'Child' ),
        array( 'Kinbok', 'Leader' ),
        array( 'Kinzon', 'Sharp', NULL, '[6]' ),
        array( 'Klo', 'Sand' ),
        array( 'Klov', 'Head' ),
        array( 'Ko', 'In' ),
        array( 'Kod', 'Wield' ),
        array( 'Kodaav', 'Bear' ),
        array( 'Kogaan', 'Blessing' ),
        array( 'Kos', 'Be/Are', '&quot;Fen Kos&quot; - &quot;Will Be&quot;' ),
        array( 'Kol', 'Crag' ),
        array( 'Komeyt', 'Issue / Issued / Let loose', 'verb' ),
        array( 'Konahrik', 'Warlord' ),
        array( 'Koor', 'Summer' ),
        array( 'Kopraan', 'Body' ),
        array( 'Kotin', 'Into' ),
        array( 'Krah', 'Cold' ),
        array( 'Krasaar', 'Sickness' ),
        array( 'Kreh', 'Bend' ),
        array( 'Kren', 'Break' ),
        array( 'Krent', 'Broken' ),
        array( 'Krein', 'Sun', 'see also &quot;Shul&quot;' ),
        array( 'Krif', 'Fight' ),
        array( 'Krii', 'Kill' ),
        array( 'Kriid', 'Slayer' ),
        array( 'Kril', 'Brave' ),
        array( 'Krilot', 'Valiant' ),
        array( 'Krin', 'Courageous' ),
        array( 'Kro', 'Sorceror' ),
        array( 'Kron', 'Conquer' ),
        array( 'Krongrah', 'Victory' ),
        array( 'Kroniid', 'Conqueror' ),
        array( 'Krosis', 'Sorrow or Alas', 'often used as an apology' ),
        array( 'Kruziik', 'Ancient' ),
        array( 'Kul', 'Son(s)' ),
        array( 'Kulaan', 'Prince' ),
        array( 'Kulaas', 'Princess' ),
        array( 'Kun', 'Light', 'Opposite of &quot;Vokun&quot; (Shadow)' ),
        array( 'Laan', 'Slowly', 'Opposite of &quot;Volaan&quot; (Quickly)' ),
        array( 'Laas', 'Life' ),
        array( 'Laat', 'Last' ),
        array( 'Lah', 'Magicka' ),
        array( 'Lahney', 'Live' ),
        array( 'Lahvraan', 'Mustered' ),
        array( 'Lahvu', 'Army' ),
        array( 'Leh', 'Lest' ),
        array( 'Lein', 'World', 'Mundus - the universe, everything' ),
        array( 'Liiv', 'Wither' ),
        array( 'Liivrah', 'Diminish' ),
        array( 'Lingrah', 'Long', '&quot;Lingrah vod&quot; = &quot;long ago&quot;' ),
        array( 'Lo', 'Deceive' ),
        array( 'Loan', 'Question' ),
        array( 'Lok', 'Sky' ),
        array( 'Loost', 'Hath' ),
        array( 'Los', 'Is', 'Combine with other verbs for present tense: &quot;is helping&quot;, &quot;is sworn&quot; etc' ),
        array( 'Lost', 'Have / Was' ),
        array( 'Lot', 'Great' ),
        array( 'Lovaas', 'Music / Song' ),
        array( 'Luft', 'Face' ),
        array( 'Lun', 'Leech' ),
        array( 'Luv', 'Tear / Tears' ),
        array( 'Maar', 'Terror', 'may also be \'self\' as the word Geinmaar\' translates to \'oneself" and \'Gein\' alone translates to \'one\'' ),
        array( 'Mah', 'Fall / Fell' ),
        array( 'Mahfaeraak', 'Forever' ),
        array( 'Mal', 'Little' ),
        array( 'Med', 'Like / Similar to' ),
        array( 'Mey', 'Fool', 'noun or verb' ),
        array( 'Meyz', 'Come', 'i.e. Meyz fundein - &quot;Come unfurled' ),
        array( 'Miin', 'Eye / Eyes' ),
        array( 'Mindok', 'Know / Known / Knowable' ),
        array( 'Mir', 'Allegiance' ),
        array( 'Miraad', 'Doorway' ),
        array( 'Monah', 'Mother' ),
        array( 'Monahven', 'Throat of the world', 'translates directly to Mother Wind', '[2]' ),
        array( 'Moro', 'Glory' ),
        array( 'Morokei', 'Glorious' ),
        array( 'Motaad', 'Shudder / Shuddered' ),
        array( 'Morah', 'Focus' ),
        array( 'Motmah', 'Slip' ),
        array( 'Motmahus', 'Slippery,Elusive' ),
        array( 'Mu', 'We' ),
        array( 'Mul', 'Strong' ),
        array( 'Mulaag', 'Strength' ),
        array( 'Mun', 'Man' ),
        array( 'Munax', 'Cruel' ),
        array( 'Muz', 'Men', 'Plural of &quot;Man&quot;, see also &quot;Jul&quot;' ),
        array( 'Naak', 'Eat' ),
        array( 'Naako', 'Eaten' ),
        array( 'Naal', 'By' ),
        array( 'Naan', 'Any' ),
        array( 'Nah', 'Fury' ),
        array( 'Nahgahdinok', 'Necromancer' ),
        array( 'Nahkip', 'Feed' ),
        array( 'Nahkriin', 'Vengeance' ),
        array( 'Nahl', 'Living', 'as in &quot;alive&quot;' ),
        array( 'Nahlaas', 'Alive' ),
        array( 'Nahlot', 'Silenced' ),
        array( 'Nau', 'On' ),
        array( 'Nax', 'Cruelty' ),
        array( 'Neh', 'Never' ),
        array( 'Ney', 'Both' ),
        array( 'Ni', 'Not' ),
        array( 'Nii', 'It' ),
        array( 'Nid or Niid', 'No' ),
        array( 'Nivahriin', 'Cowardly' ),
        array( 'Nimaar', 'Itself' ),
        array( 'Nin', 'Sting' ),
        array( 'Nir', 'Hunt' ),
        array( 'Nis', 'Cannot' ),
        array( 'Nok', 'Lie(s)', 'verb (Here lies...) and/or noun (He told a lie)' ),
        array( 'Nol', 'From' ),
        array( 'Nonvul', 'Noble' ),
        array( 'Norok', 'Fierce / Fiercest' ),
        array( 'Nu', 'Now' ),
        array( 'Nus', 'Statue' ),
        array( 'Nust', 'They' ),
        array( 'Nuz', 'But' ),
        array( 'Oblaan', 'End' ),
        array( 'Od', 'Snow' ),
        array( 'Ofan', 'Give' ),
        array( 'Ogiim', 'Orc' ),
        array( 'Ok', 'His', 'used equally with the &quot;ii&quot; form of the possessive' ),
        array( 'Okaaz', 'Sea' ),
        array( 'Ol', 'As' ),
        array( 'Om', 'Hair' ),
        array( 'Ond', 'Lo' ),
        array( 'Onik', 'Old' ),
        array( 'Onikaan', 'Wisdom' ),
        array( 'Ont', 'Once' ),
        array( 'Orin', 'Even', 'adverb, meaning &quot;Fully&quot; or &quot;Quite&quot;' ),
        array( 'Osos', 'Same' ),
        array( 'Ov', 'Trust' ),
        array( 'Paak', 'Shame' ),
        array( 'Paal', 'Foe / Enemy' ),
        array( 'Paar', 'Ambition' ),
        array( 'Paaz', 'Fair' ),
        array( 'Pah', 'All' ),
        array( 'Pahlok', 'Arrogance' ),
        array( 'Peyt', 'Rose' ),
        array( 'Pindaar', 'Plain(s)' ),
        array( 'Pogaan', 'Many' ),
        array( 'Pogaas', 'Much' ),
        array( 'Pook', 'Stink' ),
        array( 'Praan', 'Rest' ),
        array( 'Prem', 'Patience' ),
        array( 'Prodah', 'Foretell / Foretold' ),
        array( 'Pruzah', 'Good' ),
        array( 'Pruzaan', 'Best' ),
        array( 'Qahnaar/iin', 'Vanquish/er', NULL, '[4]' ),
        array( 'Qeth', 'Bone' ),
        array( 'Qethsegol', 'Stone', 'literally &quot;bone of the Earth&quot;' ),
        array( 'Qo', 'Lightning' ),
        array( 'Qolaas', 'Herald' ),
        array( 'Qostiid', 'Prophecy' ),
        array( 'Qoth', 'Tomb', NULL, '[8]' ),
        array( 'Raan', 'Animal' ),
        array( 'Rahgol', 'Rage' ),
        array( 'Rein', 'Roar' ),
        array( 'Rek', 'She', '<used equally with the &quot;ii&quot; form of possessive' ),
        array( 'Revak', 'Sacred' ),
        array( 'Reyliik', 'Race / Races', 'Heritage' ),
        array( 'Rii', 'Essence' ),
        array( 'Riik', 'Gale' ),
        array( 'Rinik', 'Very' ),
        array( 'Ro', 'Balance' ),
        array( 'Rok', 'He' ),
        array( 'Ronax', 'Regiment' ),
        array( 'Ronaan', 'Archer' ),
        array( 'Ronaaz', 'Arrow' ),
        array( 'Ronit', 'Rival', 'verb' ),
        array( 'Rotmulaag', 'Words of Power', NULL, '[2]' ),
        array( 'Rovaan', 'Wander' ),
        array( 'Ru', 'Run' ),
        array( 'Rul', 'When' ),
        array( 'Ruvaak', 'Raven' ),
        array( 'Ruz', 'Then', '&quot;ahrk ruz&quot; = &quot;and then&quot;' ),
        array( 'Sadon', 'Gray' ),
        array( 'Saraan', 'Waited' ),
        array( 'Sah', 'Phantom' ),
        array( 'Sahlo', 'Weak' ),
        array( 'Sahqo', 'Red' ),
        array( 'Sahqon', 'Crimson' ),
        array( 'Sahrot', 'Mighty' ),
        array( 'Sahsunaar', 'Villager(s)' ),
        array( 'Saviik', 'Savior' ),
        array( 'Se', 'Of', 'Of the' ),
        array( 'Shul', 'Sun' ),
        array( 'Siiv', 'Find / Found' ),
        array( 'Sil', 'Soul' ),
        array( 'Sinak', 'Finger / Fingers' ),
        array( 'Sinon', 'Instead' ),
        array( 'Sivaas', 'Beast' ),
        array( 'Sizaan', 'Lost' ),
        array( 'Slen', 'Flesh' ),
        array( 'Smoliin', 'Passion' ),
        array( 'Sonaan', 'Bard' ),
        array( 'Sos', 'Blood' ),
        array( 'Sot', 'White' ),
        array( 'Spaan', 'Shield' ),
        array( 'Staadnau', 'Unbound' ),
        array( 'Stin', 'Free', 'adjective' ),
        array( 'Strun', 'Storm' ),
        array( 'Strunmah', 'Mountain' ),
        array( 'Su', 'Air' ),
        array( 'Sul', 'Day' ),
        array( 'Suleyk', 'Power' ),
        array( 'Sunvaar', 'Beast / Beasts' ),
        array( 'Su\'um', 'Breath' ),
        array( 'Tah', 'Pack' ),
        array( 'Taazokaan', 'Tamriel', 'the physical land / continent' ),
        array( 'Tafiir', 'Thief' ),
        array( 'Tahrodiis', 'Treacherous' ),
        array( 'Tey', 'Tale' ),
        array( 'Thur', 'Tyranny', 'listed as &quot;Overlord&quot; in Skyrim Game Guide' ),
        array( 'Thu\'um', 'Shout', 'Storm Voice' ),
        array( 'Tiid', 'Time' ),
        array( 'Tinvaak', 'Speak / Speech' ),
        array( 'Togaat', 'Attempt' ),
        array( 'Tol', 'That' ),
        array( 'Toor', 'Inferno' ),
        array( 'Tu', 'Hammer' ),
        array( 'Tuz', 'Blade' ),
        array( 'Ufiik', 'Troll' ),
        array( 'Ul', 'Eternity' ),
        array( 'Unahzaal', 'Unending / Ceaseless / Eternal', 'less common than Unslaad' ),
        array( 'Unslaad', 'Unending / Ceaseless / Eternal' ),
        array( 'Unt', 'Try' ),
        array( 'Uznahgaar', 'Unbridled' ),
        array( 'Vaal', 'Bay', '&quot;ahst vaal&quot; = &quot;At Bay&quot;' ),
        array( 'Vaat', 'Swear / Swore' ),
        array( 'Vaaz', 'Tear' ),
        array( 'Vah', 'Spring' ),
        array( 'Vahdin', 'Maiden' ),
        array( 'Vahlok', 'Guardian' ),
        array( 'Vahriin', 'Sworn' ),
        array( 'Vahrukt', 'Memory' ),
        array( 'Vahrukiv', 'Commemorate' ),
        array( 'Vahzah', 'True' ),
        array( 'Vanmindoraan', 'Incomprehensible' ),
        array( 'Ved', 'Black' ),
        array( 'Ven', 'Wind' ),
        array( 'Vey', 'Cut' ),
        array( 'Veysun', 'Ship' ),
        array( 'Viik', 'Defeat' ),
        array( 'Viir', 'Dying' ),
        array( 'Viintaas', 'Shining' ),
        array( 'Viing', 'Wing' ),
        array( 'Vith', 'Serpent' ),
        array( 'Vo--', 'Un- prefix.', 'opposite of. e.g. unkind, unlikeable' ),
        array( 'Vod', 'Ago', '&quot;Lingrah vod&quot; - long ago' ),
        array( 'Vodahmin', 'Unremembered / Forgotten' ),
        array( 'Vokul', 'Evil', 'Literally &quot;ungood&quot;' ),
        array( 'Vokun', 'Shadow' ),
        array( 'Vol', 'Horror' ),
        array( 'Volaan', 'Quickly', 'A taunt used by Draugr, &quot;Dir Volaan!&quot;' ),
        array( 'Voth', 'With' ),
        array( 'Voth Ahkrin', 'Bravely', 'Literally &quot;With Courage&quot;' ),
        array( 'Vukein', 'Combat' ),
        array( 'Vul', 'Dark' ),
        array( 'Vulom', 'Darkness' ),
        array( 'Vulon', 'Night' ),
        array( 'Vus', 'Nirn' ),
        array( 'Wah', 'To' ),
        array( 'Wahl / Wahlaan (Past)', 'Build / Create' ),
        array( 'Wen', 'Whose' ),
        array( 'Werid', 'Praise' ),
        array( 'Win', 'Wage' ),
        array( 'Wo', 'Who', NULL, '[6]' ),
        array( 'Wuld', 'Whirlwind' ),
        array( 'Wuth', 'Wise' ),
        array( 'Yah', 'Seek' ),
        array( 'Yol', 'Fire' ),
        array( 'Yoriik', 'March' ),
        array( 'Yuvon', 'Gold / Golden', 'adjective' ),
        array( 'Zaam', 'Slave', NULL, '[8]' ),
        array( 'Zaan', 'Shout', 'noun; meaning &quot;Yell&quot;, not use of Voice Power' ),
        array( 'Zah', 'Finite' ),
        array( 'Zahkrii', 'Sword' ),
        array( 'Zahrahmiik', 'Sacrifice' ),
        array( 'Zeim', 'Through' ),
        array( 'Zeymah', 'Brother / Brothers' ),
        array( 'Zii', 'Spirit' ),
        array( 'Zin', 'Honor' ),
        array( 'Zind', 'Triumph' ),
        array( 'Zindro', 'Triumph\'s' ),
        array( 'Zofaas', 'Fearful' ),
        array( 'Zohungaar', 'Heroically' ),
        array( 'Zok', 'Most', 'as in degree, i.e. &quot;greatest&quot;' ),
        array( 'Zol', 'Zombie' ),
        array( 'Zoor', 'Legend' ),
        array( 'Zu (Zu\'u)', 'I', 'I am' ),
        array( 'Zul', 'Voice', 'the actual mortal voice, not the power of shouting' )
    );

    public static function getAlphabet() {
        return self::$alphabet;
    }

    public static function getWord( $word ) {

        $offset = ArrayUtils::search( self::$alphabet, $word );

        if( $offset == -1 ) {

            throw new Exception(

                '<strong>%s</strong> doesn\'t match a Dragon Word nor an English Word mapped
                with a Dragon Language translation or it\'s not yet know yet',

                NULL, $word
            );
        }

        return self::$alphabet[ $offset ];
    }
}